In [1]:
import pandas as pd

In [32]:
df = pd.read_csv ('tool touch detection.csv')

In [33]:
df.head()

,SESSION_INFO_ID,INTERVAL_IN_FILE,VALUE,SN,ACCL_X,ACCL_Y,ACCL_Z,BAND_ARR_1,BAND_ARR_2,BAND_ARR_3,...,BATT_LEVEL,DATE,FIRST_PACKET_TS,GW_MAC,GW_NAME,OPERATION_VALID,RSSI,TOOL_MAC,TOOL_NAME,S_I_CREATED_AT
0,6a39aff16c954755887e275fdfbcf82e,7,0,11,32767,-5269,32767,0.240264,0.149872,0.091437,...,67,30:24.0,234,E0D87D23F51F,Machine name,False,-59,C70BA91FEA15,E0000C23F51F,58:54.8
1,6a39aff16c954755887e275fdfbcf82e,20,0,24,32767,-5515,32767,0.173969,0.170729,0.091877,...,67,30:24.0,234,E0D87D23F51F,Machine name,False,-59,C70BA91FEA15,E0000C23F51F,58:54.8
2,6a39aff16c954755887e275fdfbcf82e,36,0,40,32767,-5801,32767,0.264151,0.110667,0.081432,...,67,30:24.0,234,E0D87D23F51F,Machine name,False,-59,C70BA91FEA15,E0000C23F51F,58:54.8
3,6a39aff16c954755887e275fdfbcf82e,45,0,49,32767,-6550,32767,3.655040,2.248858,1.993189,...,67,30:24.0,234,E0D87D23F51F,Machine name,False,-59,C70BA91FEA15,E0000C23F51F,58:54.8
4,6a39aff16c954755887e275fdfbcf82e,52,0,56,32767,-6103,32767,2.797805,1.304610,0.664670,...,67,30:24.0,234,E0D87D23F51F,Machine name,False,-59,C70BA91FEA15,E0000C23F51F,58:54.8

In [34]:
df.shape

(114271, 57)

In [5]:
from sklearn.model_selection import train_test_split

In [53]:
X = df.loc[:, df.columns != 'VALUE']

y = df['VALUE']

from sklearn import preprocessing

number = preprocessing.LabelEncoder()
X['S_I_CREATED_AT'] = number.fit_transform(X.S_I_CREATED_AT)
X['DATE'] = number.fit_transform(X.DATE)
X['GW_MAC'] = number.fit_transform(X.GW_MAC)
X['GW_NAME'] = number.fit_transform(X.GW_NAME)
X['TOOL_MAC'] = number.fit_transform(X.TOOL_MAC)
X['TOOL_NAME'] = number.fit_transform(X.TOOL_NAME)       
X['SESSION_INFO_ID'] = number.fit_transform(X.SESSION_INFO_ID)

C:\Users\Arie\AppData\Local\Temp/ipykernel_18392/2218193008.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['S_I_CREATED_AT'] = number.fit_transform(X.S_I_CREATED_AT)
C:\Users\Arie\AppData\Local\Temp/ipykernel_18392/2218193008.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['DATE'] = number.fit_transform(X.DATE)
C:\Users\Arie\AppData\Local\Temp/ipykernel_18392/2218193008.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['GW_MAC'] = number.fit_transform(X.GW_MAC)
C:\Users\Arie\AppData\Local\Temp/ipykernel_18392/2218193008.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['GW_NAME'] = number.fit_transform(X.GW_NAME)
C:\Users\Arie\AppData\Local\Temp/ipykernel_18392/2218193008.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['TOOL_MAC'] = number.fit_transform(X.TOOL_MAC)
C:\Users\Arie\AppData\Local\Temp/ipykernel_18392/2218193008.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['TOOL_NAME'] = number.fit_transform(X.TOOL_NAME)
C:\Users\Arie\AppData\Local\Temp/ipykernel_18392/2218193008.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['SESSION_INFO_ID'] = number.fit_transform(X.SESSION_INFO_ID)

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [55]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [57]:
y_pred = clf.predict(X_test)

In [26]:
from sklearn import metrics

In [58]:
print('F1 Score: ',metrics.f1_score(y_test, y_pred),
     'Accuracy Score: ',metrics.accuracy_score(y_test, y_pred),
     'Precision Score: ',metrics.precision_score(y_test, y_pred),
     'Recall Score: ',metrics.recall_score(y_test, y_pred))

F1 Score:  0.8803918771103818 Accuracy Score:  0.9266378857709585 Precision Score:  0.9799894123875066 Recall Score:  0.7991711276118114

In [59]:
prediction_row_check = pd.DataFrame(columns = ['y pred', 'y'])
prediction_row_check['y']=y_test
prediction_row_check['y pred']=y_pred
prediction_row_check['is prediction wrong'] = (prediction_row_check['y pred'] - prediction_row_check['y'])**2
prediction_row_check['SESSION_INFO_ID']=X_test['SESSION_INFO_ID']
prediction_row_check

        y pred  y  is prediction wrong  SESSION_INFO_ID
11803        0  0                    0              182
71437        0  0                    0                3
108970       0  0                    0              149
25862        0  0                    0              164
106129       0  0                    0              228
...        ... ..                  ...              ...
83779        0  0                    0              132
9982         0  0                    0              182
33935        0  0                    0              214
83883        0  0                    0               15
112262       0  0                    0               65

[34282 rows x 4 columns]

In [60]:
prediction_session_check=pd.DataFrame(prediction_row_check.groupby('SESSION_INFO_ID')['is prediction wrong'].mean())
prediction_session_check

                 is prediction wrong
SESSION_INFO_ID
0                           0.000000
3                           0.008463
5                           0.012987
7                           0.000000
8                           0.000000
...                              ...
275                         0.005597
276                         0.012903
277                         0.000000
278                         0.000000
280                         0.000000

[209 rows x 1 columns]

In [61]:
prediction_session_check=pd.DataFrame(prediction_row_check.groupby('SESSION_INFO_ID')['is prediction wrong'].mean())
prediction_session_check = prediction_session_check.reset_index()
prediction_session_check

     SESSION_INFO_ID  is prediction wrong
0                  0             0.000000
1                  3             0.008463
2                  5             0.012987
3                  7             0.000000
4                  8             0.000000
..               ...                  ...
204              275             0.005597
205              276             0.012903
206              277             0.000000
207              278             0.000000
208              280             0.000000

[209 rows x 2 columns]

In [65]:
statistics.mean(prediction_row_check['is prediction wrong'])

0.07336211422904149

In [64]:
import statistics
from statistics import mean
prediction_session_check['abs difference from average'] = abs(prediction_session_check['is prediction wrong']-statistics.mean(prediction_row_check['is prediction wrong']))
prediction_session_check

     SESSION_INFO_ID  is prediction wrong  abs difference from average
0                  0             0.000000                     0.073362
1                  3             0.008463                     0.064899
2                  5             0.012987                     0.060375
3                  7             0.000000                     0.073362
4                  8             0.000000                     0.073362
..               ...                  ...                          ...
204              275             0.005597                     0.067765
205              276             0.012903                     0.060459
206              277             0.000000                     0.073362
207              278             0.000000                     0.073362
208              280             0.000000                     0.073362

[209 rows x 3 columns]

In [66]:
print (prediction_session_check['abs difference from average'].mean())

0.07629818159875863

In [67]:
print (prediction_session_check['abs difference from average'].max())

0.8811833403164131

In [68]:
prediction_session_check[prediction_session_check['abs difference from average']>0.2]

     SESSION_INFO_ID  is prediction wrong  abs difference from average
43                58             0.359307                     0.285945
77               102             0.786325                     0.712963
118              156             0.954545                     0.881183
127              168             0.277108                     0.203746
170              228             0.323077                     0.249715

In [71]:
prediction_session_check[prediction_session_check['abs difference from average']>0.2]['SESSION_INFO_ID'].count()

5

In [72]:
prediction_session_check[prediction_session_check['abs difference from average']>0.1]['SESSION_INFO_ID'].count()

10

In [86]:
df_for_model_tab = pd.DataFrame(columns = ['validation metric'])
df_for_model_tab['validation metric'] = ('F1', 'Accuracy', 'Precision', 'Recall', 'max difference from error mean', 'mean difference from error mean', 'number of bigger than 0.2 differnece', 'number of bigger than 0.1 differnece')
df_for_model_tab

                      validation metric
0                                    F1
1                              Accuracy
2                             Precision
3                                Recall
4        max difference from error mean
5       mean difference from error mean
6  number of bigger than 0.2 differnece
7  number of bigger than 0.1 differnece

In [82]:
def error_per_session(X, y, model, model_name):
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) 

    
    clf = model
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    prediction_row_check = pd.DataFrame(columns = ['y pred', 'y'])
    prediction_row_check['y']=y_test
    prediction_row_check['y pred']=y_pred
    prediction_row_check['SESSION_INFO_ID']=X_test['SESSION_INFO_ID']
    prediction_row_check['is prediction wrong'] = (prediction_row_check['y pred'] - prediction_row_check['y'])**2
    
    prediction_session_check=pd.DataFrame(prediction_row_check.groupby('SESSION_INFO_ID')['is prediction wrong'].mean())
    prediction_session_check = prediction_session_check.reset_index()
    
    prediction_session_check['abs difference from average'] = abs(prediction_session_check['is prediction wrong']-statistics.mean(prediction_row_check['is prediction wrong']))
    
    df_for_model_tab[model_name] = metrics.f1_score(y_test, y_pred), metrics.accuracy_score(y_test, y_pred), metrics.precision_score(y_test, y_pred), metrics.recall_score(y_test, y_pred), prediction_session_check['abs difference from average'].max(), prediction_session_check['abs difference from average'].mean(), prediction_session_check[prediction_session_check['abs difference from average']>0.2]['SESSION_INFO_ID'].count(), prediction_session_check[prediction_session_check['abs difference from average']>0.1]['SESSION_INFO_ID'].count()

In [87]:
error_per_session(X, y, RandomForestClassifier(max_depth=2, random_state=0), 'Random Forest')
df_for_model_tab

                      validation metric  Random Forest
0                                    F1       0.882312
1                              Accuracy       0.926463
2                             Precision       0.977856
3                                Recall       0.803776
4        max difference from error mean       0.874611
5       mean difference from error mean       0.076182
6  number of bigger than 0.2 differnece       5.000000
7  number of bigger than 0.1 differnece       9.000000

In [88]:
from sklearn.tree import DecisionTreeClassifier

In [90]:
error_per_session(X, y, DecisionTreeClassifier(), 'Decision Tree')
df_for_model_tab

                      validation metric  Random Forest  Decision Tree
0                                    F1       0.882312       0.989269
1                              Accuracy       0.926463       0.992649
2                             Precision       0.977856       0.989775
3                                Recall       0.803776       0.988764
4        max difference from error mean       0.874611       0.101948
5       mean difference from error mean       0.076182       0.007351
6  number of bigger than 0.2 differnece       5.000000       0.000000
7  number of bigger than 0.1 differnece       9.000000       1.000000

In [96]:
from sklearn.ensemble import AdaBoostClassifier

In [97]:
error_per_session(X, y, AdaBoostClassifier(), 'Ada Boost')
df_for_model_tab

,validation metric,Random Forest,Decision Tree,Ada Boost
0,F1,0.882312,0.989269,0.974445
1,Accuracy,0.926463,0.992649,0.982673
2,Precision,0.977856,0.989775,0.975536
3,Recall,0.803776,0.988764,0.973356
4,max difference from error mean,0.874611,0.101948,0.088442
5,mean difference from error mean,0.076182,0.007351,0.017335
6,number of bigger than 0.2 differnece,5.000000,0.000000,0.000000
7,number of bigger than 0.1 differnece,9.000000,1.000000,0.000000